---
- name: "PM2 | Startup"
  become_user: "{{ global.user }}"
  ansible.builtin.shell: |
    source /home/{{ global.user }}/.nvm/nvm.sh
    {{ item }}
  changed_when: false
  args:
    executable: /bin/bash
  loop:
    - "sudo env PATH=$PATH:/home/{{ global.user }}/.nvm/versions/node/$(node -v)/bin pm2 startup systemd -u {{ global.user }}"
    - "sudo env PATH=$PATH:/home/{{ global.user }}/.nvm/versions/node/$(node -v)/bin pm2 startup systemd -u {{ global.user }} --hp /home/{{ global.user }}"

- name: "PM2 | LogRotate"
  become_user: "{{ global.user }}"
  ansible.builtin.shell: |
    source /home/{{ global.user }}/.nvm/nvm.sh
    {{ item }}
  changed_when: false
  args:
    executable: /bin/bash
  loop:
    - "pm2 install pm2-logrotate"
    - "pm2 set pm2-logrotate:max_size 6M"
    - "pm2 set pm2-logrotate:retain 6"
    - "pm2 set pm2-logrotate:compress true"
    - "pm2 set pm2-logrotate:workerInterval 3600"
    - "pm2 set pm2-logrotate:rotateInterval '0 12 * * 0'"

- name: "PM2 | Start"
  become_user: "{{ global.user }}"
  ansible.builtin.shell: |
    source /home/{{ global.user }}/.nvm/nvm.sh
    {{ item }}
  changed_when: false
  args:
    executable: /bin/bash
  loop:
    - "pm2 start  {{ flux_os.path }}/start.sh --max-memory-restart 2G --restart-delay 30000 --max-restarts 40 --name flux --time"

- name: "PM2 | Save"
  become_user: "{{ global.user }}"
  ansible.builtin.shell: |
    source /home/{{ global.user }}/.nvm/nvm.sh
    {{ item }}
  changed_when: false
  args:
    executable: /bin/bash
  loop:
    - "pm2 save"
