---
#
# This is the primary playbook

- name: Flux Node Install
  hosts: all
  vars_files:
    - vars.yml
    - user.yml

  tasks:
    - name: Common Role
      ansible.builtin.import_role:
        name: common

    - name: UFW Role
      ansible.builtin.import_role:
        name: ufw

    - name: Docker Role
      ansible.builtin.import_role:
        name: docker

    - name: NVM Role
      ansible.builtin.import_role:
        name: nvm

    - name: Mongo Role
      ansible.builtin.import_role:
        name: mongo

    - name: Daemon Role
      ansible.builtin.import_role:
        name: daemon

    - name: Log Rotate Role
      ansible.builtin.import_role:
        name: logrotate

    - name: Fluxbench Role
      ansible.builtin.import_role:
        name: fluxbench

    - name: FluxOS Role
      ansible.builtin.import_role:
        name: fluxos

    - name: PM2 Role
      ansible.builtin.import_role:
        name: pm2

    - name: Watchdog Role
      ansible.builtin.import_role:
        name: watchdog

    - name: IP Check Role
      ansible.builtin.import_role:
        name: ipcheck
