---
#
# This is the primary playbook

- hosts: all
  vars_files:
    - vars.yml

  tasks:
    - name: Common Role
      import_role:
        name: common

    - name: Docker Role
      import_role:
        name: docker

    - name: NVM Role
      import_role:
        name: nvm
