---
#
# This is the primary playbook

- hosts: all
  vars:
     project: FluxInstall
  vars_file:
  		- 'vars'


- name: Common Role
  import_role:
  		name: common

- name: Flux Role
  import_role:
  		name: flux