---
#
# This is the primary playbook

- name: Flux Node Install
  hosts: all
  vars_files:
    - vars.yml

  tasks:
    - name: Common Role
      ansible.builtin.import_role:
        name: common

    - name: Docker Role
      ansible.builtin.import_role:
        name: docker

    - name: NVM Role
      ansible.builtin.import_role:
        name: nvm

    - name: Daemon Role
      ansible.builtin.import_role:
        name: daemon

    - name: Sysbench Role
      ansible.builtin.import_role:
        name: sysbench
