---
#
# This is the primary playbook

- hosts: all
  vars_files:
    - vars.yml

  tasks:
    - name: Common Role
      import_role:
        name: common
      tags:
        - common
        - never

    - name: Docker Role
      import_role:
        name: docker
      tags:
        - docker
        - never

    - name: Flux Role
      import_role:
        name: flux
      tags:
        - flux
        - never
