---
#
# This is the primary playbook

- hosts: all
  vars:
     project: FluxInstall
  vars_file:
  		- 'vars.yml'


- name: Common Role
  import_role:
  		name: common

- name: Docker Role
  import_role:
  		name: flux

- name: Flux Role
  import_role:
  		name: flux