---
- name: Setup Log rotate
  ansible.builtin.template:
    src: logrotate.j2
    dest: "/etc/logrotate.d/{{ item.name }}"
    owner: root
    group: root
    mode: "0644"
  loop: "{{ logrotate.service }}"
