---
- name: Remove IP Check script
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/home/{{ global.user }}/ip_check.sh"
    - "/home/{{ global.user }}/ip_history.log"

- name: Remove Cron Entries
  ansible.builtin.cron:
    name: "{{ item.name }}"
    user: "{{ global.user }}"
    job: "{{ item.job }}"
    state: absent
  loop:
    - {name: 'Restart on boot', job: "env USER=$LOGNAME $HOME/ip_check.sh restart"}
    - {name: 'Check IP every 15 minutes', job: "env USER=$LOGNAME $HOME/ip_check.sh ip_check"}
