---
- name: Install MongoDB
  ansible.builtin.include_tasks:
    file: mongo-install.yml
    apply:
      tags:
        - mongo-install
        - mongo
        - all
      become: true
  tags:
    - mongo-install
    - mongo
    - all
    - never

- name: Remove MongoDB
  ansible.builtin.include_tasks:
    file: mongo-purge.yml
    apply:
      tags:
        - mongo-purge
        - purge
      become: true
  tags:
    - mongo-purge
    - purge
    - never
