---
- name: Detect architecture
  ansible.builtin.set_fact:
    system_arch: "{{ ansible_machine | replace('x86_64', 'amd64') | replace('aarch64', 'arm64') }}"

- name: Check AVX
  ansible.builtin.command:
    cmd: "grep -c avx /proc/cpuinfo"
  register: avx_check
  changed_when: false
  failed_when: false

- name: Remove mongo key 4.0
  ansible.builtin.apt_key:
    keyring: "{{ mongo.keyring }}"
    url: "{{ mongo.path4 }}"
    state: absent

- name: Remove mongo key 6.0
  ansible.builtin.apt_key:
    keyring: "{{ mongo.keyring }}"
    url: "{{ mongo.path6 }}"
    state: absent

- name: Remove mongo key 7.0
  ansible.builtin.apt_key:
    keyring: "{{ mongo.keyring }}"
    url: "{{ mongo.path7 }}"
    state: absent

- name: Removing APT Repository 4.0
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ system_arch }} signed-by={{ mongo.keyring }}]
     https://repo.mongodb.org/apt/{{ ansible_distribution | lower }} {{ ansible_distribution_release }}/mongodb-org/4.4 multiverse"
    state: absent
    filename: "{{ mongo.list4 }}"

- name: Remove APT Repository 6.0
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ system_arch }} signed-by={{ mongo.keyring }}]
      https://repo.mongodb.org/apt/{{ ansible_distribution | lower }} {{ ansible_distribution_release }}/mongodb-org/6.0 multiverse"
    state: absent
    filename: "{{ mongo.list6 }}"

- name: Remove APT Repository 7.0
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ system_arch }} signed-by={{ mongo.keyring }}]
      https://repo.mongodb.org/apt/{{ ansible_distribution | lower }} {{ ansible_distribution_release }}/mongodb-org/7.0 multiverse"
    state: absent
    filename: "{{ mongo.list7 }}"

- name: Remove Mongo
  ansible.builtin.apt:
    name: mongod*
    purge: true
    state: absent
    autoremove: true
    force: true
