name: Question 🤷‍♂️
description: Got a question about FluxNodeInstall, Ansible, development or usage?
title: '[QUESTION] <title>'
labels: ['🤷‍♂️ Question']

body:
  # Filed 1 - Intro Text
  - type: markdown
    attributes:
      value: >
        Thanks for using FluxNodeInstall! Questions are welcome.
    validations:
      required: false

  # Field 2 - The actual question
  - type: textarea
    id: question
    attributes:
      label: Question
      description: Outline your question in a clear and concise manner
    validations:
      required: true

  # Field 3 - User has RTFM first, and agrees to code of conduct, etc
  - type: checkboxes
    id: idiot-check
    attributes:
      label: Please tick the boxes
      description: Before submitting, please ensure that
      options:
        - label: You have explained the issue clearly, and included all relevant info
          required: true
        - label: You are using the latest version of FluxNodeInstall
          required: true
        - label: You've checked that this [issue hasn't already been raised](https://github.com/techdufus/FluxNodeInstall/issues?q=is%3Aissue)
          required: true
        - label: You agree to the [code of conduct](https://github.com/techdufus/FluxNodeInstall/blob/main/.github/CODE_OF_CONDUCT.md)
          required: true

