---
- name: Disable UFW Logging
  ansible.builtin.ufw:
    logging: false

- name: Disable UFW
  ansible.builtin.ufw:
    state: disabled

- name: Remove UFW Allow Out Defaults
  ansible.builtin.ufw:
    port: "{{ item }}"
    rule: allow
    to: any
    direction: out
    delete: true
  loop: "{{ ufw.allow_out }}"

- name: Remove UFW Allow IN Defaults
  ansible.builtin.ufw:
    port: "{{ item }}"
    rule: allow
    to: any
    direction: in
    delete: true
  loop: "{{ ufw.allow_in }}"

- name: UPnP Gateway Rule
  ansible.builtin.ufw:
    port: 1900
    protocol: udp
    to_ip: 239.255.255.250
    src: any
    direction: out
    rule: allow
    delete: true
  when:
    - hostvars[inventory_hostname].gateway
    - hostvars[inventory_hostname].apiport

- name: UPnP Router Out TCP
  ansible.builtin.ufw:
    protocol: tcp
    from: any
    to_ip: "{{ hostvars[inventory_hostname].gateway }}"
    rule: allow
    direction: out
    delete: true
  when:
    - hostvars[inventory_hostname].gateway
    - hostvars[inventory_hostname].apiport

- name: UPnP Router Out UDP
  ansible.builtin.ufw:
    protocol: udp
    from_ip: "{{ hostvars[inventory_hostname].gateway }}"
    to_ip: any
    rule: allow
    delete: true
  when:
    - hostvars[inventory_hostname].gateway
    - hostvars[inventory_hostname].apiport

- name: UPnP Router Port 1900
  ansible.builtin.ufw:
    from_port: 1900
    from_ip: "{{ hostvars[inventory_hostname].gateway }}"
    to_ip: any
    proto: udp
    rule: allow
    delete: true
  when:
    - hostvars[inventory_hostname].gateway
    - hostvars[inventory_hostname].apiport
