---
- name: Copy Daemon Start Service Script
  ansible.builtin.copy:
    dest: "/home/{{ global.user }}/start_daemon_service.sh"
    src: "../scripts/start_daemon_service.sh"
    owner: "{{ global.user }}"
    group: "{{ global.user }}"
    mode: "0755"

- name: Copy Daemon Stop Service Script
  ansible.builtin.copy:
    dest: "/home/{{ global.user }}/stop_daemon_service.sh"
    src: "../scripts/stop_daemon_service.sh"
    owner: "{{ global.user }}"
    group: "{{ global.user }}"
    mode: "0755"

- name: Copy Zelcash Service Script
  ansible.builtin.copy:
    dest: /etc/systemd/system/zelcash.service
    src: "../scripts/zelcash.service"
    owner: root
    group: root
    mode: "0644"
