---
- name: Purge Flux Daemon and Flux Bench
  ansible.builtin.apt:
    name:
      - flux
      - fluxbench
    state: absent
    autoremove: true

- name: Remove flux-archive-keyring.gpg if present
  ansible.builtin.file:
    path: "{{ daemon.keyring }}"
    state: absent

- name: Remove flux.list if present
  ansible.builtin.file:
    path: "{{ daemon.list_file }}.list"
    state: absent

- name: Remove start daemon service scripts
  ansible.builtin.file:
    path: "/home/{{ global.user }}/start_daemon_service.sh"
    state: absent

- name: Remove stop daemon service scripts
  ansible.builtin.file:
    path: "/home/{{ global.user }}/stop_daemon_service.sh"
    state: absent

- name: Remove zelcash servie script
  ansible.builtin.file:
    path: /etc/systemd/system/zelcash.service
    state: absent
