---
- name: Detect architecture
  ansible.builtin.set_fact:
    system_arch: "{{ ansible_machine | replace('x86_64', 'amd64') | replace('aarch64', 'arm64') }}"

- name: Add GPG Keys
  ansible.builtin.apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: 4B69CA27A986265D
    keyring: "{{ daemon.keyring }}"

- name: Add Daemon APT Repository
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ system_arch }} signed-by={{ daemon.keyring }}] https://apt.runonflux.io/ {{ ansible_distribution_release }} main"
    state: present
    filename: "{{ daemon.list_file }}"

- name: Install Flux Daemon and Bench
  ansible.builtin.apt:
    name:
      - flux
      - fluxbench
    update_cache: true
    state: present

- name: Install Flux Daemon Service "{{ daemon.service_name }}"
  ansible.builtin.copy:
    dest: "/etc/systemd/system/{{ daemon.service_name }}"
    src: "{{ daemon.service_name }}"
    owner: root
    group: root
    mode: "0644"

- name: Reload and enable "{{ daemon.service_name }}"
  ansible.builtin.systemd:
    name: "{{ daemon.service_name }}"
    daemon_reload: true
    enabled: true

- name: Verify Permissions
  ansible.builtin.file:
    path: "/usr/local/bin"
    mode: "0755"
    state: directory
