---
- name: Purge Flux Daemon and Flux Bench
  ansible.builtin.apt:
    name:
      - flux
      - fluxbench
    state: absent
    autoremove: true

- name: Remove flux-archive-keyring.gpg if present
  ansible.builtin.file:
    path: /usr/share/keyrings/flux-archive-keyring.gpg
    state: absent

- name: Remove flux.list if present
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/flux.list
    state: absent
