---
- name: Purge Flux Daemon and Flux Bench
  ansible.builtin.apt:
    name:
      - flux
      - fluxbench
    state: absent
    autoremove: true

- name: Detect architecture
  ansible.builtin.set_fact:
    system_arch: "{{ ansible_machine | replace('x86_64', 'amd64') | replace('aarch64', 'arm64') }}"

- name: Remove GPG Keys
  ansible.builtin.apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: 4B69CA27A986265D
    keyring: "{{ daemon.keyring }}"
    state: absent

- name: Remove Daemon APT Repository
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ system_arch }} signed-by={{ daemon.keyring }}] https://apt.runonflux.io/ {{ ansible_distribution_release }} main"
    state: absent
    filename: "{{ daemon.list_file }}"

- name: Remove start / stop daemon service scripts
  ansible.builtin.file:
    path: "/home/{{ global.user }}/{{ item }}"
    state: absent
  loop:
    - "start_daemon_service.sh"
    - "stop_daemon_service.sh"

- name: Remove "{{ daemon.service_name }}"
  ansible.builtin.file:
    path: "/etc/systemd/system/{{ daemon.service_name }}"
    state: absent

- name: Reload and enable "{{ daemon.service_name }}"
  ansible.builtin.systemd:
    daemon_reload: true
