---
- name: Download Daemon Boostrap
  ansible.builtin.include_tasks:
    file: daemon-bootstrap.yml
    apply:
      tags:
        - daemon-bootstrap
        - daemon
      become: true
  tags:
    - daemon-bootstrap
    - daemon
    - never

- name: Install Flux Daemon and Flux Bench
  ansible.builtin.include_tasks:
    file: daemon-install.yml
    apply:
      tags:
        - daemon-install
        - daemon
      become: true
  tags:
    - daemon-install
    - daemon
    - never

- name: Remove Flux Daemon and Bench
  ansible.builtin.include_tasks:
    file: daemon-purge.yml
    apply:
      tags:
        - daemon-purge
        - pugre
      become: true
  tags:
    - daemon-purge
    - pugre
    - never

- name: ZKsnark Fetch
  ansible.builtin.include_tasks:
    file: daemon-zksnark.yml
    apply:
      tags:
        - daemon-zksnark
        - daemon
      become: true
  tags:
    - daemon-zksnark
    - daemon
    - never

- name: Daemon Scripts
  ansible.builtin.include_tasks:
    file: daemon-scripts.yml
    apply:
      tags:
        - daemon-scripts
        - daemon
      become: true
  tags:
    - daemon-scripts
    - daemon
    - never
