---
- name: Remove Flux Daemon and Bench
  ansible.builtin.include_tasks:
    file: daemon-purge.yml
    apply:
      tags:
        - daemon-purge
        - purge
      become: true
  tags:
    - daemon-purge
    - purge
    - never

- name: Daemon Scripts
  ansible.builtin.include_tasks:
    file: daemon-scripts.yml
    apply:
      tags:
        - daemon-scripts
        - daemon
        - all
      become: true
  tags:
    - daemon-scripts
    - daemon
    - all
    - never

- name: Daemon Conf File
  ansible.builtin.include_tasks:
    file: daemon-conf.yml
    apply:
      tags:
        - daemon-conf
        - daemon
        - all
      become: true
  tags:
    - daemon-conf
    - daemon
    - all
    - never

- name: Install Flux Daemon and Flux Bench
  ansible.builtin.include_tasks:
    file: daemon-install.yml
    apply:
      tags:
        - daemon-install
        - daemon
        - all
      become: true
  tags:
    - daemon-install
    - daemon
    - all
    - never

- name: Download Daemon Boostrap
  ansible.builtin.include_tasks:
    file: daemon-bootstrap.yml
    apply:
      tags:
        - daemon-bootstrap
        - daemon
        - all
      become: true
  tags:
    - daemon-bootstrap
    - daemon
    - all
    - never
