---
- name: Download Daemon Boostrap
  ansible.builtin.include_tasks:
    file: daemon-bootstrap.yml
    apply:
      tags:
        - daemon-bootstrap
        - daemon
      become: true
  tags:
    - daemon-bootstrap
    - daemon
    - never

- name: Install Daemon from Apt
  ansible.builtin.include_tasks:
    file: daemon-install.yml
    apply:
      tags:
        - daemon-install
        - daemon
      become: true
  tags:
    - daemon-install
    - daemon
    - never
