---
- name: Get public IP using ipify
  ansible.builtin.uri:
    url: "{{ ip.url1 }}"
    return_content: true
  register: public_ip
  ignore_errors: true

- name: Get public IP using api4.my-ip.io
  ansible.builtin.uri:
    url: "{{ ip.url2 }}"
    return_content: true
  register: public_ip_fallback
  when: public_ip is failed

- name: Set WANIP ternary
  ansible.builtin.set_fact:
    wanip: "{{ public_ip is success | ternary(public_ip.content, public_ip_fallback.content) }}"
