---
- name: Detect architecture
  ansible.builtin.set_fact:
    system_arch: "{{ ansible_machine | replace('x86_64', 'amd64') | replace('aarch64', 'arm64') }}"

- name: Gather facts
  ansible.builtin.setup:

- name: Add Docker GPG key and APT repository
  ansible.builtin.apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg

- name: Add APT Repository
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ system_arch }} signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present
    filename: /etc/apt/sources.list.d/docker.list

- name: Install Docker
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    update_cache: true
    state: present

- name: Add current user to docker group
  ansible.builtin.user:
    name: "{{ global.user }}"
    groups: docker
    append: true

- name: Start Docker service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
