---
- name: Install Docker
  ansible.builtin.include_tasks:
    file: docker-install.yml
    apply:
      tags:
        - docker-purge
        - docker
      become: true
  tags:
    - docker-purge
    - docker
    - never

- name: Install Docker
  ansible.builtin.include_tasks:
    file: docker-install.yml
    apply:
      tags:
        - docker-install
        - docker
      become: true
  tags:
    - docker-install
    - docker
    - never
