---
- name: Stop Docker service and socket
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false
  with_items:
    - docker
    - docker.socket
  ignore_errors: true

- name: Purge Docker-related packages
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - runc
    state: absent

- name: Remove docker-archive-keyring.gpg if present
  ansible.builtin.file:
    path: /usr/share/keyrings/docker-archive-keyring.gpg
    state: absent

- name: Remove docker.list if present
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/docker.list
    state: absent

- name: Gather facts
  ansible.builtin.setup:

- name: Add Docker GPG key and APT repository
  ansible.builtin.apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg

- name: Add APT Repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present
    filename: /etc/apt/sources.list.d/docker.list

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Autoremove unused packages
  ansible.builtin.apt:
    autoremove: true
    purge: true

- name: Install Docker
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: Add current user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true

- name: Start Docker service
  ansible.builtin.service:
    name: docker
    state: started
